/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountistItem: typeof import('./src/components/AccountistItem.vue')['default']
    AccountListItem: typeof import('./src/components/AccountListItem.vue')['default']
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Copy_ShowReservationDialog: typeof import('./src/components/dialog/copy_ShowReservationDialog.vue')['default']
    CreateReservationDialog: typeof import('./src/components/dialog/CreateReservationDialog.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    DropdownItem: typeof import('./src/components/DropdownItem.vue')['default']
    EditPetDialog: typeof import('./src/components/dialog/EditPetDialog.vue')['default']
    EditReservationDialog: typeof import('./src/components/dialog/EditReservationDialog.vue')['default']
    EditUserDialog: typeof import('./src/components/dialog/EditUserDialog.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FieldSet: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Fluid: typeof import('primevue/fluid')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MetadataEditor: typeof import('./src/components/MetadataEditor.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NewPetDialog: typeof import('./src/components/dialog/NewPetDialog.vue')['default']
    NewReservatioDialog: typeof import('./src/components/dialog/NewReservatioDialog.vue')['default']
    NewUserDialog: typeof import('./src/components/dialog/NewUserDialog.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    ReservationListItem: typeof import('./src/components/ReservationListItem.vue')['default']
    ReservationSlots: typeof import('./src/components/ReservationSlots.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    ShowPetDialog: typeof import('./src/components/dialog/ShowPetDialog.vue')['default']
    ShowReservationDialog: typeof import('./src/components/dialog/ShowReservationDialog.vue')['default']
    ShowUserDialog: typeof import('./src/components/dialog/ShowUserDialog.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Spacer: typeof import('./src/components/Spacer.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UserBadge: typeof import('./src/components/UserBadge.vue')['default']
  }
}
