name = "y2p-app"
compatibility_date = "2024-12-27"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./dist" }
pages_build_output_dir = "./dist"
[build]
command = "bun run build"
cwd = "."
[observability.logs]
enabled = true
[vars]
VITE_API_URL = "http://localhost:8787/api"
